### ISSUE TITLE
Multi instance?

### ISSUE THREAD

**Issue by horsto** [pykeras/multiclass_semantic_segemnet#1]
Thanks for providing this example! Very helpful. How would you go about extending this to multi instance + multi class?

**Comment by pykeras** [comment]
Hi
Can you provide any sample dataset?

I can't figure out what you mean. I think the current example could solve it.

**Comment by pykeras** [comment]
Hi @horsto 
Can you provide any sample dataset?

I can't figure out what you mean. I think the current example could solve it.

**Comment by horsto** [comment]
Thank you @pykeras - turns out I was confused myself about the terminology. Thanks again for providing the example code!
